### ISSUE TITLE
Doesn't work on Chrome OS X Mojave 

### ISSUE THREAD

**Issue by andreydos** [Inndy/vue-clipboard2#59] opened 2019-04-25 12:06 UTC
Bind 'copy' funtion to button: 
function copy(val) {
        this.$copyText(val).then(() => {
          console.log('success')
        }, () => {
          console.log('error')
        })
      }

in console, I get message 'success', but actually clipboard stay without change (value not saves in system clipboard). Funny thing if I set "debugger" in the begin of fuction, and in chrome tools press resume "value" copies to system clipboard

**Comment by Inndy** [comment] 2019-04-29 03:32
Can not reproduce. Please provide a minimal (not) working example.

**Comment by sydCPT** [comment] 2019-05-03 13:24
I am having the same issue.  It works correctly and copies the value on Safari, but not on Chrome and Firefox.  Same as with andreydos, the console log reports that the value was copied successfully, but it is not in the clipboard

`<span
  title="Copy to clipboard"
  class="link headline"
  v-clipboard:copy="wholeorder.orderreference"
  v-clipboard:success="copyOrderRefToClipboard"
>{{wholeorder.orderreference }}</span>`

`copyValueToClipboard: function (e) {
  console.log(`Copied: ${e.text}`)
  this.copiedSnackbar = true
  this.copiedSnackbarValue = `${e.text} copied to clipboard.`
}`

This in on MacOS Mojave 10.14.4
Using NPM
Vue: vue@2.6.10
Vuetify: vuetify@1.5.14

**Comment by M3psipax** [comment] 2019-05-27 14:02
Hey guys, I just had this issue with the vuetify modal and I solved it fyi:

My problem was that it didn't work when I was trying to copy a string directly without any html element while a vuetify modal was open.

Turns out I just had to RTFM, because it's addressed in the description of this repo.
But setting `autoSetContainer` didn't work for me since I was just passing along a string.
Instead, I had to make a reference to an element inside the modal and pass it along like so:

`this.$copyText(text, this.$refs.copyContainer.$el)`

it's important to pass $el as opposed to just the ref because that is the underlying HTML element that the fake element is attached to.

hope this'll help some people. Cheers!

**Comment by ctwhome** [comment] 2019-06-10 15:07
> Hey guys, I just had this issue with the vuetify modal and I solved it fyi:
> 
> My problem was that it didn't work when I was trying to copy a string directly without any html element while a vuetify modal was open.
> 
> Turns out I just had to RTFM, because it's addressed in the description of this repo.
> But setting `autoSetContainer` didn't work for me since I was just passing along a string.
> Instead, I had to make a reference to an element inside the modal and pass it along like so:
> 
> `this.$copyText(text, this.$refs.copyContainer.$el)`
> 
> it's important to pass $el as opposed to just the ref because that is the underlying HTML element that the fake element is attached to.
> 
> hope this'll help some people. Cheers!

this saved me thank you for posting. Same scenario, Vuetify with a v-dialog opened. 
 vue@2.6.10 and vuetify@1.5.15

**Comment by sydCPT** [comment] 2019-06-19 19:14
> Turns out I just had to RTFM, because it's addressed in the description of this repo.

Thanks for pointing me in the right direction, I should  have paid more attention and RTFM!

**Comment by gwh-cpnet** [comment] 2019-08-28 10:04
Thanks @M3psipax , I run into this problem with vuetify too. a working example look like this

```html
<v-dialog v-model="isRawVisible" max-width="90%" persistent @keydown.esc="isRawVisible = false;">
  <v-card>
    <v-card-actions>
      <v-btn small icon @click="doCopy" ref="container">
        <v-icon small>mdi-content-copy</v-icon>
      </v-btn>
    </v-card-actions>
  </v-card>
</v-dialog>
```

```js
async doCopy() {
  return this.$copyText(this.raw, this.$refs.container.$el);
},
```

just `ref` the button as the container.

**Closed** 2019-10-28 08:11 UTC

**Comment by ggedde** [comment] 2020-01-02 06:36
I had the same issue.
I just needed to add the following line in my config
```
VueClipboard.config.autoSetContainer = true // add this line
```

**Comment by dikkini** [comment] 2020-07-02 10:24
> I had the same issue.
> I just needed to add the following line in my config
> 
> ```
> VueClipboard.config.autoSetContainer = true // add this line
> ```

this does not work for me

vuejs, vuejs-bootstrap

**Comment by darkman97i** [comment] 2021-12-08 10:33
I have the same problem, when copy is done into a popup does not work, finally I success solve with the next code:
```javascript
this.$copyText(this.text, this.$root.$el); // getting the root element of the app
```
